<?php
include_once('includes/header.php');
include_once('includes/navigation.php');
include_once('includes/slider.php');
include_once('includes/random_recipe.php');
include_once('includes/trending_recipe.php');
include_once('includes/editor_choice_recipe.php');
include_once('includes/popular_recipe.php');
include_once('includes/footer.php');
